### ISSUE TITLE
Issue with Portrait Format

### ISSUE THREAD

**Issue by Fcenotif** [michaelsoriano/bootstrap-photo-gallery#1]
Hi,

First thing, nice job! It works well with Lanscape format. But when you add Portrait format picture, it become more complicated.

First point (major): Portrait picture is not well defined. Huger than landscape and  need to scroll to click next.
Second point (more minor): Column resize is space

Best regards.
Frederic

**Comment by michaelsoriano** [comment]
good catch. let me look into this.

**Comment by michaelsoriano** [comment]
I was just now able to fix this issue. If you look at the new demo - it now supports variable height for images.
