### ISSUE TITLE
show img can't be middle in vertical direction 

### ISSUE THREAD

**Issue by mqy1023** [michaelsoriano/bootstrap-photo-gallery#11]
show img can't be middle in vertical direction;

**Comment by michaelsoriano** [comment]
can you tell me how to replicate

**Comment by mqy1023** [comment]
as you ![demo view](https://camo.githubusercontent.com/23c6ec6e52d7f5f8401c9371094fbf8d21690409/687474703a2f2f6d69636861656c736f7269616e6f2e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031332f31312f62737067616c6c6572792e676966) show,  the image is not in vertical center

**Comment by mqy1023** [comment]
i modify bootstrap.min.css source,  ‘.modal.in .modal-dialog’ and ‘.modal-dialog’
```
.modal.in .modal-dialog {
        -webkit-transform:translate(0,-50%);-ms-transform:translate(0,-50%);-o-transform:translate(0,-50%);transform:translate(0,-50%)
}
.modal-dialog {
     position:absolute;width:auto;margin:10px auto;left:0;right:0;top:50%
}
```
it work as what i want.thanks!

**Comment by michaelsoriano** [comment]
I have a unique ID for the modal which you should prepend into your CSS: #bsPhotoGalleryModal. 
This will prevent your new styles to interfere with the default Bootstrap Behavior.
