### ISSUE TITLE
displaying multiple galleries on the same page

### ISSUE THREAD

**Issue by kir12** [michaelsoriano/bootstrap-photo-gallery#14]
I folllowed the instructions to set up a photo gallery using the plugin, and it works for one gallery. But when I try implementing a second gallery, one gallery overlaps another. How would I go about resolving this issue?

Here's a screenshot of what's happening:
![selection_036](https://user-images.githubusercontent.com/11183158/29194600-6bbceb46-7df8-11e7-9a50-c30cfd061528.png)

**Comment by michaelsoriano** [comment]
Try separating your galleries with a div. Ideally one that has a clear:both.

**Comment by michaelsoriano** [comment]
closing issue
