### ISSUE TITLE
How do I make the full size files popup?

### ISSUE THREAD

**Issue by michalstepniewski** [michaelsoriano/bootstrap-photo-gallery#15]
Hello.
I would like to make the full size versions of pictures to pop out. (like full screen are almost) I see that sometimes pictures are shown with full height.
How can I achieve this or maybe make the popup window bigger?
Should I edit the JS or CSS file?

Sincerely

Michal

**Comment by michaelsoriano** [comment]
You can edit the CSS and override the .modal-dialog or .modal-lg bootstrap classes. Right now it's restricting it to 600px / 900px. Simply increase that wider. 

So in your CSS file: 

`@media (min-width: 992px){
.modal-lg {
    width: YOURWIDTH;
}
}
`
and 

`
@media (min-width: 768px){
.modal-dialog {
    width: YOURWIDTH
}
}
`
