### ISSUE TITLE
bootstrap v4 breaks sizing and arrows

### ISSUE THREAD

**Issue by pschloss** [michaelsoriano/bootstrap-photo-gallery#16]
When I use bootstrap v4 rather than v3.3.5, I'm noticing places where bootstrap-photo-gallery breaks...

* the thumbnails no long represent the entire image and instead are all the same size and contain the upper left corner of the image rather than the entire width of the image.

<img width="1138" alt="screen shot 2017-12-30 at 3 29 39 pm" src="https://user-images.githubusercontent.com/1264132/34457154-552c1e54-ed76-11e7-8267-4f21187c6b56.png">

* the glyphicons to close and move left/right in modal mode are gone

<img width="847" alt="screen shot 2017-12-30 at 3 29 49 pm" src="https://user-images.githubusercontent.com/1264132/34457153-55142f92-ed76-11e7-9c48-18fce7e57081.png">

Any ideas on a fix for this? When I use bootstrap v.3.3.5, it looks like yours, but the rest of my site is using v.4, so I'd like to stick with the more recent version.

**Comment by michaelsoriano** [comment]
I have a branch for [bootstrap 4](https://github.com/michaelsoriano/bootstrap-photo-gallery/tree/bootstrap-4) - which is still in progress. hope to be done with it real soon

**Comment by michaelsoriano** [comment]
master branch is now using B4
