### ISSUE TITLE
Thumbnails support 

### ISSUE THREAD

**Issue by AsoStrife** [michaelsoriano/bootstrap-photo-gallery#18]
Is it possibile to add native support to thumbnails?
Someting like 

````
<li>
   <a href="source.jpg">
        <img alt="img"  src=" thumbnail.jpg">
        <p>Some text</p>
    </a>
</li>````

**Comment by michaelsoriano** [comment]
I think it will simply open the image by default. you can set the "hasModal" to false so it won't trigger the modal.
