### ISSUE TITLE
Including a download image in the modal popup

### ISSUE THREAD

**Issue by BillCBos** [michaelsoriano/bootstrap-photo-gallery#20]
This may be already baked in but I don't know the coding well enough to decipher what I need to do. I would like to include a link and clickable icon that will prompt for the download of the image presented in the modal popup. Can you provide me with some insight and direction? Thank you.

**Comment by BillCBos** [comment]
I have made this update to the photo-gallery.js file. 

		html += img;                
		// original height  html += '<div style="height:25px;clear:both;display:block;">';
		html += '<div style="height:50px;clear:both;display:block;">';
		// my attempt at creating a download link
		html += '<a class="bc-center" href="' + src + '"  download>Click to Download <button type="button" class="glyphicon-download"></button></a>';
                // end 
		html += '<a class="controls next" href="'+ (index+2) + '">next &raquo;</a>';
		html += '<a class="controls previous" href="' + (index) + '">&laquo; prev</a>';
		html += '</div>';
I wasn't able to get the css right to put the download in between the prev-next labels. Here's the css I added to my page: 
	.bc-center 
		  {float: inherit;
		  text-align: center;
		  display:block;
      	  font-size:11px;
          padding-top:8px;
          font-weight:bold }

It's good for now. If you have a better, more elegant solution or can tell my how to get the download link in line and in-between the prev-next labels instead of increasing the the height of the box, please let me know. Thanks.

**Comment by michaelsoriano** [comment]
Closing this case - as it's not a supported feature at the moment.
