### ISSUE TITLE
Broken grid on some sizes

### ISSUE THREAD

**Issue by NathanHazout** [michaelsoriano/bootstrap-photo-gallery#3]
I took your idea and adapted it to a video gallery.

See: http://jsfiddle.net/mk2r974o/

Sometimes it looks fine:
![screen shot 2015-11-01 at 4 51 33 pm](https://cloud.githubusercontent.com/assets/329834/10869453/e5336c82-80b8-11e5-8d34-6754fcf29519.png)

Sometimes it puts one of the videos on the right:
![screen shot 2015-11-01 at 4 51 40 pm](https://cloud.githubusercontent.com/assets/329834/10869454/f2289f98-80b8-11e5-9ad5-a16319137781.png)

I can't catch what the differences are in the code....

**Comment by michaelsoriano** [comment]
Hi @nasht00, 

I updated the code to support variable heights for the images. See the new demo: https://rawgit.com/michaelsoriano/bootstrap-photo-gallery/master/demo.html 

Basically you need to add an element that will clear the items. Bootstrap has a class for this called "clearfix".

The element needs to be added where you want them to clear. For example, if you're using "col-lg-2" (which means 6 columns), right after the 6th image, you add the element

 In addition, you have to add helper classes to only make them appear at certain viewports, such as "visible-lg-block"

So the element will have classes like below: 

"clearfix visible-lg-block"

![variable-height](https://cloud.githubusercontent.com/assets/5881081/10873803/d5cacf68-80ce-11e5-9c64-b7073163b162.jpg)

**Comment by NathanHazout** [comment]
Thank you.
That's going to be a pain when the list is dynamically generated by code...

**Comment by michaelsoriano** [comment]
Yes it looks like a bit of a challenge writing it dynamically. You should look into http://masonry.desandro.com/. This can go on top of what you already have.
