### ISSUE TITLE
improvement 

### ISSUE THREAD

**Issue by darkman97i** [michaelsoriano/bootstrap-photo-gallery#7]
I've done few improvements ( replace anchors by buttons and set description at the center bottom ), if you consider useful take it. I suppose this is not the right way for giving you, but I ignore what is the correct one. I will use your photo gallery to show screenshot of an application and I little description in the screenshot is necessary to illustrate what is seeing.

Also in your demo.html file I needed to change the line ( possible bug with missing http ? )

<script src="//code.jquery.com/jquery-1.10.2.min.js"></script>

to <script src="http://code.jquery.com/jquery-1.10.2.min.js"></script>

You can download the files from here http://www.fast-files.com/getfile.aspx?file=100722

**Comment by michaelsoriano** [comment]
Thank you @darkman97i. I'm actually converting this into a plugin. It's almost done and merging soon.

**Comment by darkman97i** [comment]
These are good news, thanks for your great work.

**Comment by michaelsoriano** [comment]
Plugin code is up.

**Comment by darkman97i** [comment]
Thanks for the notice. I've done some experiment to adapt image gallery to video gallery, if you consider interesting use it. https://github.com/darkman97i/bootstrap-photo-gallery ( I think changes are minimal )
